dist: trusty
sudo: required
python:
- "2.7"

before_install:
- sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
- sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116
- sudo apt-get update
- sudo apt-get install -q python2.7 python2.7-dev python-setuptools python-pip python-numpy python-pytest ros-indigo-rosbag ros-indigo-roslz4 postgresql-server-dev-9.6
- (git clone https://github.com/Kozea/Multicorn && cd Multicorn && make && sudo make install)
- sudo pip install 'flake8==3.3.0'

install:
- sudo pip install .

script:
- flake8 fdwli3ds
- source /opt/ros/indigo/setup.bash && py.test -v test

after_success:
  - 'test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && curl -H
    "Content-Type: application/json" -X POST https://registry.hub.docker.com/u/li3ds/li3ds/trigger/$DOCKER_API_KEY/'

env:
  global:
    secure: hJeJ+9rXWZk32eB48JHQ/iYR+vzYJO6RHZvD4SPAql4veVJxFu6DN6tybER+kGV/IkFjCms8zmaxOaqj76W06Qv8bOIlpcgk0vu3dYtdtoDJ7ospgyjXwLso9zrpSJaaI14qSqASmDpOUJFbbxrtkaM3YdF5JUnSo8P3ETeaCqYYYHOjew6Oc46PY0TMoWKjcWqC+ObzQyAgFgj13wfK+/7oeCPytiasrJ0Dz6MrrC4qdbfLMvFrXU9lHxy73nr9Hxy3sK8YYzHMu/t2izJF8LmrnoTQc2jgv6LhUQ5KpESNYNwC4NKNqTmkRUN52Pu1CrlXVs1gs5EygfVlQA3YrxVoOQRswsL0IrPYG639RnFAX4kXWQaNggSLGPot9rn17GCb68bWE62K2/ze5ufgOuHiplReaPk/XT7ONQqC/fF9iiZbP9kEvIP4XlGBrOzyzxfcmlTvZVWh2KrQUAm3mo4XaaLiSwDFM4ayXlOdHEtUpD1ozdmQRJagDWXbnhxWKl/bPb+FmJKQ4PYnVN6r44CtPNFroWysLivkJCLbX5emqxMTbbOK7f87vCxTO4Z/OEVUdeQo8ehLh++mhh9YJER1G5WEQyXq/SuVgGzV3gg/kCDdKW9Dc3QcU1ZZbOFDtLCUBgbKgosUYP+m1S1cFPNHOE30qcnj4hWPo9IBuIs=
